pipeline {
    agent any
         stages {

            stage('Step1') {
                git 'https://github.com/fhoton/DevOps_learning.git'





                           }
            stage('Step2') {






                           }
            
            stage('Step3') {






                           }


                }
         
         
         }